In [2]:
import os
import pandas as pd

In [4]:
config = {"user_genre_dist_file":"./cornac/data_c/user_genre_dist.csv"}

actual_genre_dist = pd.read_csv(
            os.path.join(config["user_genre_dist_file"]),
            sep="\t",
        )
actual_genre_dist

,userID,Action,Thriller,Romance,Western,Children's,Mystery,Fantasy,Film-Noir,Documentary,Comedy,Adventure,Sci-Fi,Horror,Crime,Musical,War,Animation,Drama
0,0,0.029031,0.038749,0.054221,0.000000,0.128900,0.000000,0.017419,0.000000,0.000000,0.128687,0.024023,0.017418,0.000000,0.015483,0.087993,0.019415,0.148294,0.290368
1,1,0.157693,0.088141,0.061218,0.009615,0.000000,0.004808,0.002404,0.002404,0.000000,0.089744,0.047917,0.046314,0.003205,0.033654,0.000000,0.034295,0.000000,0.418588
2,2,0.147967,0.050813,0.017886,0.069106,0.013008,0.008130,0.014228,0.000000,0.000000,0.346342,0.176423,0.034146,0.012195,0.000000,0.004878,0.009756,0.013008,0.082113
3,3,0.376471,0.044118,0.011765,0.029412,0.014706,0.000000,0.029412,0.000000,0.000000,0.000000,0.106863,0.116667,0.063726,0.000000,0.000000,0.043137,0.000000,0.163725
4,4,0.071803,0.080713,0.072851,0.006289,0.012054,0.012054,0.000000,0.005241,0.037736,0.190775,0.014151,0.018868,0.033543,0.042453,0.006813,0.015723,0.010482,0.368449
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6035,6035,0.070938,0.086496,0.062260,0.009961,0.022997,0.014182,0.007197,0.007735,0.009141,0.179744,0.032422,0.083882,0.049272,0.026958,0.013807,0.015916,0.015681,0.291411
6036,6036,0.045794,0.169743,0.047321,0.010802,0.009774,0.025718,0.006175,0.019548,0.003086,0.172829,0.010807,0.083893,0.016977,0.033948,0.009772,0.026237,0.000000,0.307577
6037,6037,0.031249,0.000000,0.125001,0.000000,0.031249,0.000000,0.000000,0.000000,0.000000,0.364577,0.000000,0.000000,0.062498,0.000000,0.000000,0.062500,0.062501,0.260424
6038,6038,0.018855,0.053029,0.099998,0.006734,0.041582,0.069864,0.017676,0.026941,0.000000,0.290737,0.031489,0.028114,0.003367,0.000000,0.153532,0.028958,0.033167,0.095958
6039,6039,0.052331,0.062353,0.055394,0.006269,0.003783,0.016861,0.004657,0.009945,0.025703,0.191522,0.024500,0.052110,0.049449,0.025007,0.013040,0.025994,0.001164,0.379918

In [19]:
x = actual_genre_dist[actual_genre_dist["Documentary"]>0.00]
movies = pd.read_csv("./cornac/data_c/indexed_movies.csv")

movies = movies.drop(columns=movies.columns[0])

In [11]:
users = pd.read_csv("./cornac/data_c/u_id_mapping.csv", sep="\t")
users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)

In [17]:

rating_data_pd = pd.read_csv(
    "./cornac/data_c/indexed_interactions.csv",
    sep="\t",
    header=None,
    names=["userID", "itemID", "Rating", "Timestamp"],
)
# print(rating_data["itemID"].nunique())
# rating_data = rating_data.drop(columns=rating_data.columns[-1])
rating_data = rating_data_pd.to_numpy()
rating_data

array([[        0,         0,         5, 978300760],
       [        0,         1,         3, 978302109],
       [        0,         2,         3, 978301968],
       ...,
       [     6039,       365,         5, 956704746],
       [     6039,       152,         4, 956715648],
       [     6039,        26,         4, 956715569]])

In [24]:
m = pd.merge(rating_data_pd, movies, on="itemID", how="inner")
m

,userID,itemID,Rating,Timestamp,movieID,genres
0,0,0,5,978300760,1193,Drama
1,0,1,3,978302109,661,Animation|Children's|Musical
2,0,2,3,978301968,914,Musical|Romance
3,0,3,4,978300275,3408,Drama
4,0,4,5,978824291,2355,Animation|Children's|Comedy
...,...,...,...,...,...,...
999606,6039,772,1,956716541,1091,Comedy
999607,6039,1106,5,956704887,1094,Drama|Romance|War
999608,6039,365,5,956704746,562,Comedy|Drama
999609,6039,152,4,956715648,1096,Drama
999610,6039,26,4,956715569,1097,Children's|Drama|Fantasy|Sci-Fi

In [25]:
x = m[m["genres"].__contains__("Documentary")]

KeyError: False