In [6]:
import cornac
from cornac.data import Reader
from cornac.datasets import movielens
from cornac.data import Dataset, FeatureModality
from cornac.eval_methods import RatioSplit, StratifiedSplit
from cornac.metrics import RMSE, AUC, NDCG, Precision, Recall
from cornac.models import MF, ItemKNN, UserKNN, NMF, BPR, LightGCN, SVD, MostPop, VAECF, NeuMF
import pandas as pd
import numpy as np
import random
import math
from collections import OrderedDict
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
reader = Reader()
rating_data_pd = pd.read_csv(
    "./cornac/data_c/ml-100k/indexed_interactions.csv",
    sep="\t",
    header=None,
    names=["userID", "itemID", "Rating", "Timestamp"],
)
rating_data = rating_data_pd.to_numpy()
rating_data.__len__()
rating_data_pd
df_m = pd.read_csv(
    "./cornac/data_c/ml-100K/u.item",
    sep="|",
    names=[
        "movieID",
        "Name",
        "Date",
        "Video_Date",
        "IMDB_URL",
        "unknown",
        "Action",
        "Adventure",
        "Animation",
        "Children's",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Fantasy",
        "Film-Noir",
        "Horror",
        "Musical",
        "Mystery",
        "Romance",
        "Sci-Fi",
        "Thriller",
        "War",
        "Western",
    ],
    header=None,
    encoding="latin-1",
)
print(df_m.shape)
df_m = df_m[
    [
        "movieID",
        "Action",
        "Adventure",
        "Animation",
        "Children's",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Fantasy",
        "Film-Noir",
        "Horror",
        "Musical",
        "Mystery",
        "Romance",
        "Sci-Fi",
        "Thriller",
        "War",
        "Western",
    ]
]

df_movies_mapped = pd.read_csv(
    "./cornac/data_c/ml-100K/i_id_mapping.csv",
    sep="\t",
    names=["movieID", "itemID"],
    header=None,
    encoding="latin-1",
)
movies = pd.merge(df_m, df_movies_mapped, how="inner", on="movieID")
movies

(1682, 24)

,movieID,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,itemID
0,1,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,24
1,2,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,147
2,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,233
3,4,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,47
4,5,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1344,1592,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1305
1345,1597,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1324
1346,1598,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1319
1347,1615,1,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1341
1348,1620,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1337

In [3]:
movies = movies.drop(columns=["movieID"])
movies = movies.sort_values(by="itemID")

In [4]:

unique_genres = [
    "Action",
    "Thriller",
    "Romance",
    "Western",
    "Children's",
    "Mystery",
    "Fantasy",
    "Film-Noir",
    "Documentary",
    "Comedy",
    "Adventure",
    "Sci-Fi",
    "Horror",
    "Crime",
    "Musical",
    "War",
    "Animation",
    "Drama",
]
genre = movies[unique_genres]
item_features_numpy = genre.to_numpy()

users = pd.read_csv("./cornac/data_c/ml-100k/u_id_mapping.csv", sep="\t")

users = users.sort_values(by="userID")

users = users.drop(columns=users.columns[0])
gender_map = {"M": 0, "F": 1}
users["Gender"] = users["Gender"].map(gender_map)
user_features_numpy = users.to_numpy()
users
def create_genre_column(r):
    all_genres = [g for g in unique_genres if r[g] == 1]
    return "|".join(all_genres)


movies["genres"] = movies.apply(create_genre_column, axis=1)
movies

,Action,Adventure,Animation,Children's,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,itemID,genres
240,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,Comedy
300,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1,Thriller|Mystery|Film-Noir|Crime
375,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,2,Children's|Comedy
50,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,1,3,Romance|Western|War|Drama
344,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,4,Crime|Drama
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1248,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1344,Drama
1192,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1345,Comedy
1176,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1346,Drama
1261,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1347,Drama
1327,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1348,Comedy

In [5]:
dataset = rating_data
unique_genres.__len__()

18

In [14]:
rec_50 = cornac.metrics.Recall(k=50)
ndcg_50 = cornac.metrics.NDCG(k=50)
auc = cornac.metrics.AUC()
rmse = cornac.metrics.RMSE()
prec = cornac.metrics.Precision(k=50)
hr = cornac.metrics.HitRatio(k=50)
mrr = cornac.metrics.MRR()
map = cornac.metrics.MAP()
ratio_split = StratifiedSplit(
    data=dataset,
    test_size=0.2,
    rating_threshold=0,
    val_size=0.1,
    seed=123,
    verbose=True,
    chrono=True,
    user_features=user_features_numpy[:, 0],
    item_features=item_features_numpy,
    exclude_unknowns=False,
)
models = []
model_1 = UserKNN(k=20, seed=123, verbose=True)
model_2 = ItemKNN(k=20, seed=123, verbose=True)
model_3 = MF(
            k=20,
            seed=123,
            name=f"a={0} mf",
            backend="pytorch",
            verbose=True,
            optimizer="adam",batch_size=256,
            alpha=0,
            learning_rate=0.001,
            top_k=50, max_iter=20,
            # early_stopping=True
        )
model_4 = VAECF(k=32,
        autoencoder_structure=[60,40],
        act_fn="relu",
        likelihood="bern",
        n_epochs=50,
        batch_size=128,
        learning_rate=0.0005,
        alpha=0,
        top_k=50,
        beta=1,
        name=f"a={0} vae",
        seed=123,
        verbose=True,
        # early_stopping=True)
)
# model_5 = NeuMF(num_factors=8, layers=[32,16,8], act_fn="relu", num_epochs=64, batch_size=256, num_neg=3, backend="pytorch", lr=0.001, alp=0, top_k=50, name=str(0)+ "neumf")
# models.append(model_5)

models.append(model_1)
models.append(model_2)
models.append(model_3)
models.append(model_4)

   
cornac.Experiment(
    ratio_split, models=models, metrics=[rec_50, ndcg_50, auc, rmse, prec, hr, mrr, map]
).run()

rating_threshold = 0.0
exclude_unknowns = False
::::::::
OrderedDict()
OrderedDict()
::::::::
---
Training data:
(array([  0,   0,   0, ..., 942, 942, 942]), array([  0,   1,   2, ..., 880, 632, 261]), array([4., 4., 4., ..., 1., 5., 4.]))
Number of users = 943
Number of items = 1348
Number of ratings = 68674
Max rating = 5.0
Min rating = 1.0
Global mean = 3.6
Global mean Imolicit= 1.0
::::::::
OrderedDict([(101, 0), (845, 1), (705, 2), (20, 3), (635, 4), (593, 5), (153, 6), (37, 7), (915, 8), (522, 9), (810, 10), (18, 11), (34, 12), (809, 13), (239, 14), (749, 15), (889, 16), (928, 17), (542, 18), (501, 19), (342, 20), (175, 21), (116, 22), (144, 23), (618, 24), (118, 25), (860, 26), (335, 27), (263, 28), (825, 29), (405, 30), (942, 31), (867, 32), (286, 33), (393, 34), (224, 35), (146, 36), (792, 37), (416, 38), (652, 39), (147, 40), (368, 41), (773, 42), (727, 43), (194, 44), (246, 45), (75, 46), (446, 47), (76, 48), (461, 49), (793, 50), (912, 51), (110, 52), (504, 53), (84, 54), (627, 55), (621, 56), (42, 57), (594, 58), (728, 59), (301, 60), (214, 61), (668, 62), (937, 63), (484, 64), (274, 65), (685, 66), (526, 67), (776, 68), (121, 69), (139, 70), (108, 71), (679, 72), (207, 73), (111, 74), (65, 75), (587, 76), (143, 77), (322, 78), (392, 79), (770, 80), (299, 81), (838, 82), (690, 83), (630, 84), (27, 85), (829, 86), (11, 87), (676, 88), (26, 89), (380, 90), (490, 91), (378, 92), (706, 93), (909, 94), (781, 95), (98, 96), (463, 97), (772, 98), (795, 99), (662, 100), (883, 101), (12, 102), (487, 103), (721, 104), (703, 105), (771, 106), (448, 107), (551, 108), (759, 109), (767, 110), (397, 111), (95, 112), (596, 113), (339, 114), (198, 115), (192, 116), (869, 117), (219, 118), (658, 119), (645, 120), (49, 121), (878, 122), (315, 123), (683, 124), (361, 125), (639, 126), (409, 127), (738, 128), (935, 129), (28, 130), (289, 131), (691, 132), (512, 133), (882, 134), (367, 135), (407, 136), (681, 137), (158, 138), (545, 139), (137, 140), (107, 141), (125, 142), (852, 143), (29, 144), (537, 145), (364, 146), (864, 147), (255, 148), (895, 149), (178, 150), (713, 151), (161, 152), (317, 153), (862, 154), (432, 155), (711, 156), (278, 157), (701, 158), (334, 159), (834, 160), (465, 161), (391, 162), (363, 163), (149, 164), (220, 165), (56, 166), (70, 167), (22, 168), (813, 169), (74, 170), (602, 171), (383, 172), (131, 173), (329, 174), (535, 175), (133, 176), (905, 177), (436, 178), (264, 179), (39, 180), (578, 181), (800, 182), (689, 183), (477, 184), (82, 185), (574, 186), (472, 187), (345, 188), (92, 189), (469, 190), (922, 191), (814, 192), (450, 193), (808, 194), (729, 195), (754, 196), (417, 197), (300, 198), (222, 199), (491, 200), (636, 201), (841, 202), (742, 203), (649, 204), (440, 205), (103, 206), (640, 207), (694, 208), (2, 209), (758, 210), (223, 211), (485, 212), (356, 213), (35, 214), (71, 215), (445, 216), (244, 217), (59, 218), (1, 219), (188, 220), (270, 221), (156, 222), (920, 223), (473, 224), (530, 225), (24, 226), (567, 227), (186, 228), (549, 229), (801, 230), (16, 231), (215, 232), (856, 233), (272, 234), (647, 235), (73, 236), (850, 237), (932, 238), (599, 239), (182, 240), (665, 241), (106, 242), (10, 243), (89, 244), (913, 245), (588, 246), (870, 247), (389, 248), (225, 249), (365, 250), (904, 251), (418, 252), (273, 253), (560, 254), (152, 255), (302, 256), (332, 257), (903, 258), (498, 259), (787, 260), (377, 261), (295, 262), (585, 263), (696, 264), (805, 265), (241, 266), (419, 267), (358, 268), (797, 269), (243, 270), (430, 271), (249, 272), (726, 273), (835, 274), (404, 275), (746, 276), (677, 277), (611, 278), (794, 279), (573, 280), (468, 281), (756, 282), (102, 283), (126, 284), (743, 285), (128, 286), (120, 287), (527, 288), (628, 289), (849, 290), (476, 291), (901, 292), (609, 293), (159, 294), (346, 295), (15, 296), (349, 297), (354, 298), (138, 299), (17, 300), (737, 301), (764, 302), (129, 303), (227, 304), (622, 305), (460, 306), (940, 307), (735, 308), (321, 309), (31, 310), (488, 311), (261, 312), (684, 313), (710, 314), (457, 315), (320, 316), (45, 317), (531, 318), (213, 319), (789, 320), (582, 321), (413, 322), (57, 323), (386, 324), (846, 325), (423, 326), (414, 327), (906, 328), (260, 329), (898, 330), (44, 331), (401, 332), (443, 333), (680, 334), (540, 335), (96, 336), (620, 337), (708, 338), (566, 339), (281, 340), (150, 341), (851, 342), (702, 343), (78, 344), (881, 345), (435, 346), (478, 347), (310, 348), (54, 349), (240, 350), (833, 351), (892, 352), (539, 353), (384, 354), (548, 355), (212, 356), (831, 357), (441, 358), (304, 359), (572, 360), (204, 361), (91, 362), (408, 363), (482, 364), (802, 365), (555, 366), (64, 367), (894, 368), (53, 369), (369, 370), (798, 371), (122, 372), (865, 373), (626, 374), (736, 375), (185, 376), (114, 377), (173, 378), (151, 379), (661, 380), (434, 381), (863, 382), (899, 383), (875, 384), (885, 385), (81, 386), (938, 387), (127, 388), (731, 389), (783, 390), (766, 391), (352, 392), (918, 393), (366, 394), (603, 395), (284, 396), (174, 397), (569, 398), (32, 399), (202, 400), (559, 401), (233, 402), (303, 403), (740, 404), (557, 405), (374, 406), (791, 407), (181, 408), (663, 409), (327, 410), (429, 411), (3, 412), (763, 413), (752, 414), (815, 415), (624, 416), (914, 417), (907, 418), (283, 419), (425, 420), (876, 421), (782, 422), (390, 423), (237, 424), (130, 425), (919, 426), (591, 427), (570, 428), (200, 429), (722, 430), (733, 431), (518, 432), (817, 433), (406, 434), (55, 435), (6, 436), (755, 437), (682, 438), (257, 439), (197, 440), (0, 441), (183, 442), (590, 443), (866, 444), (732, 445), (141, 446), (256, 447), (454, 448), (890, 449), (187, 450), (253, 451), (58, 452), (666, 453), (282, 454), (558, 455), (343, 456), (564, 457), (493, 458), (77, 459), (447, 460), (166, 461), (704, 462), (30, 463), (553, 464), (117, 465), (550, 466), (135, 467), (816, 468), (644, 469), (442, 470), (532, 471), (394, 472), (360, 473), (421, 474), (803, 475), (453, 476), (888, 477), (565, 478), (525, 479), (672, 480), (762, 481), (753, 482), (617, 483), (583, 484), (687, 485), (873, 486), (265, 487), (847, 488), (235, 489), (47, 490), (779, 491), (444, 492), (634, 493), (924, 494), (458, 495), (123, 496), (580, 497), (494, 498), (228, 499), (848, 500), (242, 501), (199, 502), (529, 503), (9, 504), (60, 505), (517, 506), (716, 507), (592, 508), (614, 509), (470, 510), (437, 511), (290, 512), (552, 513), (692, 514), (891, 515), (861, 516), (479, 517), (99, 518), (279, 519), (502, 520), (251, 521), (221, 522), (464, 523), (589, 524), (298, 525), (513, 526), (113, 527), (112, 528), (288, 529), (619, 530), (201, 531), (61, 532), (511, 533), (497, 534), (720, 535), (79, 536), (839, 537), (719, 538), (399, 539), (505, 540), (523, 541), (259, 542), (607, 543), (536, 544), (496, 545), (604, 546), (218, 547), (837, 548), (822, 549), (210, 550), (579, 551), (136, 552), (160, 553), (41, 554), (896, 555), (584, 556), (5, 557), (483, 558), (428, 559), (686, 560), (154, 561), (85, 562), (941, 563), (659, 564), (33, 565), (86, 566), (516, 567), (351, 568), (660, 569), (88, 570), (675, 571), (734, 572), (786, 573), (921, 574), (226, 575), (69, 576), (191, 577), (784, 578), (285, 579), (929, 580), (519, 581), (877, 582), (697, 583), (231, 584), (238, 585), (933, 586), (715, 587), (395, 588), (698, 589), (157, 590), (309, 591), (547, 592), (931, 593), (340, 594), (341, 595), (43, 596), (268, 597), (900, 598), (336, 599), (163, 600), (449, 601), (355, 602), (313, 603), (509, 604), (744, 605), (544, 606), (247, 607), (520, 608), (673, 609), (40, 610), (459, 611), (709, 612), (853, 613), (812, 614), (109, 615), (761, 616), (375, 617), (402, 618), (275, 619), (633, 620), (632, 621), (403, 622), (46, 623), (533, 624), (820, 625), (306, 626), (884, 627), (826, 628), (712, 629), (575, 630), (855, 631), (168, 632), (556, 633), (481, 634), (563, 635), (83, 636), (51, 637), (90, 638), (422, 639), (615, 640), (534, 641), (252, 642), (521, 643), (93, 644), (745, 645), (48, 646), (8, 647), (456, 648), (688, 649), (206, 650), (818, 651), (455, 652), (4, 653), (717, 654), (97, 655), (382, 656), (373, 657), (67, 658), (379, 659), (347, 660), (538, 661), (887, 662), (372, 663), (638, 664), (433, 665), (741, 666), (939, 667), (610, 668), (601, 669), (293, 670), (568, 671), (87, 672), (842, 673), (524, 674), (828, 675), (910, 676), (748, 677), (893, 678), (595, 679), (66, 680), (314, 681), (650, 682), (480, 683), (796, 684), (507, 685), (515, 686), (13, 687), (23, 688), (311, 689), (387, 690), (879, 691), (671, 692), (431, 693), (499, 694), (203, 695), (648, 696), (467, 697), (318, 698), (858, 699), (105, 700), (14, 701), (169, 702), (262, 703), (236, 704), (868, 705), (52, 706), (832, 707), (230, 708), (902, 709), (297, 710), (936, 711), (258, 712), (167, 713), (750, 714), (598, 715), (629, 716), (871, 717), (211, 718), (674, 719), (656, 720), (765, 721), (229, 722), (769, 723), (508, 724), (277, 725), (193, 726), (411, 727), (500, 728), (489, 729), (886, 730), (597, 731), (739, 732), (172, 733), (605, 734), (232, 735), (561, 736), (667, 737), (699, 738), (370, 739), (707, 740), (68, 741), (785, 742), (305, 743), (854, 744), (208, 745), (641, 746), (145, 747), (184, 748), (276, 749), (269, 750), (859, 751), (148, 752), (307, 753), (471, 754), (196, 755), (426, 756), (381, 757), (700, 758), (287, 759), (657, 760), (195, 761), (410, 762), (362, 763), (466, 764), (725, 765), (162, 766), (503, 767), (613, 768), (506, 769), (576, 770), (179, 771), (451, 772), (462, 773), (250, 774), (806, 775), (291, 776), (164, 777), (190, 778), (50, 779), (777, 780), (94, 781), (338, 782), (836, 783), (439, 784), (248, 785), (747, 786), (730, 787), (916, 788), (581, 789), (897, 790), (396, 791), (333, 792), (623, 793), (824, 794), (799, 795), (245, 796), (19, 797), (823, 798), (554, 799), (843, 800), (788, 801), (664, 802), (216, 803), (412, 804), (475, 805), (844, 806), (923, 807), (807, 808), (292, 809), (562, 810), (388, 811), (528, 812), (543, 813), (324, 814), (655, 815), (124, 816), (348, 817), (669, 818), (495, 819), (927, 820), (385, 821), (654, 822), (830, 823), (171, 824), (474, 825), (751, 826), (840, 827), (323, 828), (872, 829), (612, 830), (616, 831), (631, 832), (925, 833), (625, 834), (723, 835), (217, 836), (331, 837), (350, 838), (209, 839), (398, 840), (328, 841), (571, 842), (718, 843), (586, 844), (934, 845), (424, 846), (541, 847), (514, 848), (492, 849), (344, 850), (36, 851), (371, 852), (180, 853), (359, 854), (768, 855), (608, 856), (115, 857), (930, 858), (38, 859), (821, 860), (415, 861), (486, 862), (775, 863), (646, 864), (142, 865), (80, 866), (780, 867), (104, 868), (874, 869), (420, 870), (695, 871), (757, 872), (326, 873), (400, 874), (357, 875), (176, 876), (165, 877), (132, 878), (651, 879), (917, 880), (637, 881), (100, 882), (337, 883), (693, 884), (642, 885), (271, 886), (510, 887), (234, 888), (819, 889), (760, 890), (312, 891), (308, 892), (857, 893), (353, 894), (778, 895), (140, 896), (316, 897), (325, 898), (438, 899), (62, 900), (170, 901), (330, 902), (7, 903), (774, 904), (134, 905), (606, 906), (319, 907), (189, 908), (880, 909), (254, 910), (205, 911), (827, 912), (177, 913), (811, 914), (452, 915), (72, 916), (926, 917), (600, 918), (155, 919), (911, 920), (267, 921), (643, 922), (266, 923), (427, 924), (296, 925), (653, 926), (280, 927), (25, 928), (804, 929), (790, 930), (119, 931), (670, 932), (376, 933), (546, 934), (21, 935), (714, 936), (908, 937), (577, 938), (294, 939), (63, 940), (678, 941), (724, 942)])

100%|██████████| 943/943 [00:00<00:00, 53720.54it/s]

[UserKNN] Evaluation started!

Rating: 100%|██████████| 20242/20242 [00:00<00:00, 35334.93it/s]

::::::
0.6498019173704298

Ranking: 100%|██████████| 943/943 [00:02<00:00, 338.99it/s]
Rating: 100%|██████████| 10371/10371 [00:00<00:00, 32628.20it/s]

::::::
0.7083455148559576

Ranking: 100%|██████████| 943/943 [00:02<00:00, 419.87it/s]

[ItemKNN] Training started!

100%|██████████| 1348/1348 [00:00<00:00, 51570.88it/s]

[ItemKNN] Evaluation started!

Rating: 100%|██████████| 20242/20242 [00:00<00:00, 28609.22it/s]

::::::
0.6755420019090802

Ranking: 100%|██████████| 943/943 [00:04<00:00, 218.54it/s]
Rating: 100%|██████████| 10371/10371 [00:00<00:00, 27281.35it/s]

::::::
0.7724238366538844

Ranking: 100%|██████████| 943/943 [00:03<00:00, 237.98it/s]

[a=0 mf] Training started!

100%|██████████| 20/20 [00:02<00:00,  7.48it/s, loss=0.514]

[294.7196044921875, 361.0678405761719, 320.986083984375, 307.817626953125, 280.4860534667969, 350.66461181640625, 298.8372802734375, 303.0100402832031, 280.9540100097656, 325.2540283203125, 339.8428649902344, 310.67205810546875, 310.7219543457031, 307.5111083984375, 257.5977783203125, 335.1020202636719, 280.0852355957031, 309.46307373046875, 288.895751953125, 317.80975341796875, 292.32568359375, 298.1026916503906, 308.71685791015625, 294.02252197265625, 292.5393371582031, 277.7213439941406, 298.2445983886719, 306.4815673828125, 280.97564697265625, 294.1807861328125, 347.7889709472656, 274.00201416015625, 329.1974792480469, 345.2244873046875, 325.98504638671875, 322.4717102050781, 318.4559326171875, 315.2992858886719, 310.25299072265625, 312.83349609375, 300.51885986328125, 297.691162109375, 307.5010681152344, 278.891357421875, 308.2222900390625, 310.82513427734375, 294.1680908203125, 309.798583984375, 257.1056213378906, 286.3899841308594, 295.3870849609375, 256.8753662109375, 282.25555419921875, 315.81878662109375, 314.2230224609375, 313.3865051269531, 303.3759765625, 331.6776428222656, 326.6433410644531, 307.51629638671875, 293.0859375, 326.20745849609375, 321.4241027832031, 328.14117431640625, 263.4845275878906, 279.56268310546875, 312.5506591796875, 343.8216857910156, 312.0649108886719, 283.14312744140625, 283.9306640625, 303.25653076171875, 322.2335510253906, 283.20526123046875, 269.00360107421875, 324.76971435546875, 289.04949951171875, 314.2734375, 303.7213134765625, 291.1468200683594, 281.6586608886719, 289.6564025878906, 249.5830078125, 292.4621276855469, 301.4175720214844, 286.3067321777344, 318.46966552734375, 327.3714294433594, 267.4173889160156, 273.1170654296875, 282.5279541015625, 315.1988220214844, 298.67535400390625, 303.7914733886719, 277.6218566894531, 307.5431823730469, 329.43115234375, 258.48443603515625, 297.266357421875, 307.74932861328125, 316.5409240722656, 266.4566345214844, 290.78375244140625, 289.0677795410156, 268.98724365234375, 286.627685546875, 288.1711120605469, 321.5405578613281, 349.55548095703125, 293.7972412109375, 348.13525390625, 321.58843994140625, 282.4634704589844, 313.0684509277344, 262.83404541015625, 321.73065185546875, 305.87017822265625, 278.8928527832031, 313.02587890625, 268.76068115234375, 285.617919921875, 337.2301940917969, 294.3917236328125, 286.4551086425781, 263.65631103515625, 256.87774658203125, 318.2945251464844, 328.6405029296875, 279.954345703125, 258.04437255859375, 305.58343505859375, 302.2563781738281, 325.5528564453125, 284.1967468261719, 273.7019348144531, 347.7446594238281, 306.8192138671875, 295.3594665527344, 305.93499755859375, 297.83697509765625, 249.95755004882812, 327.6101379394531, 303.5344543457031, 280.2610168457031, 314.8188171386719, 241.93203735351562, 313.78814697265625, 336.18670654296875, 289.79296875, 292.8661193847656, 273.0972900390625, 311.6688537597656, 337.88262939453125, 351.65423583984375, 270.3426513671875, 266.3233642578125, 305.7933654785156, 259.5893249511719, 271.81280517578125, 257.9571533203125, 271.2007751464844, 284.50372314453125, 316.6191101074219, 281.1381530761719, 268.40008544921875, 299.2154235839844, 302.03582763671875, 296.9056701660156, 256.26806640625, 291.9102783203125, 293.8752746582031, 264.4801025390625, 296.447998046875, 276.26214599609375, 308.2745361328125, 298.17108154296875, 300.956787109375, 290.03546142578125, 307.8705139160156, 302.7580871582031, 290.48785400390625, 242.70999145507812, 336.6217041015625, 311.95892333984375, 297.88372802734375, 290.31390380859375, 303.8988037109375, 310.6876220703125, 238.5565185546875, 266.66741943359375, 298.579345703125, 303.083740234375, 313.5740966796875, 239.51116943359375, 265.0824279785156, 267.6875915527344, 304.87762451171875, 297.659912109375, 303.54449462890625, 267.2630310058594, 340.1601257324219, 251.26791381835938, 256.20660400390625, 259.16363525390625, 262.7969665527344, 263.5256042480469, 270.0163269042969, 310.474609375, 301.59893798828125, 284.9942321777344, 243.04165649414062, 292.34686279296875, 286.65191650390625, 296.50238037109375, 274.59228515625, 257.4955139160156, 245.9308624267578, 267.1908264160156, 303.88897705078125, 261.73162841796875, 287.2350158691406, 283.67413330078125, 321.3564453125, 277.41143798828125, 276.0218200683594, 299.55279541015625, 319.5205993652344, 311.3154602050781, 279.204345703125, 314.1969909667969, 287.12457275390625, 258.4666748046875, 250.279052734375, 275.3211975097656, 272.82708740234375, 258.359619140625, 280.06976318359375, 271.58642578125, 313.00775146484375, 302.71429443359375, 296.4656982421875, 220.53201293945312, 314.928955078125, 306.7220764160156, 264.37274169921875, 278.61138916015625, 307.837890625, 343.943603515625, 308.9718933105469, 284.4453430175781, 342.3092346191406, 292.4418640136719, 280.34039306640625, 256.2353820800781, 264.0838623046875, 284.2545166015625, 293.6678161621094, 285.47222900390625, 279.3708190917969, 291.72314453125, 271.32879638671875, 293.6352844238281, 233.92100524902344, 285.15008544921875, 288.9908142089844, 269.89166259765625, 280.16583251953125, 277.47991943359375, 63.131309509277344, 213.39776611328125, 292.8440856933594, 283.01422119140625, 247.48484802246094, 268.2806701660156, 265.4986572265625, 323.3540954589844, 278.41510009765625, 271.4186706542969, 265.24395751953125, 242.47178649902344, 299.3953552246094, 240.57489013671875, 261.1125793457031, 243.6504669189453, 281.1073303222656, 269.0757141113281, 270.04071044921875, 280.8155517578125, 267.4469909667969, 266.6429138183594, 279.1836242675781, 271.95428466796875, 262.75445556640625, 252.9842071533203, 260.7511291503906, 295.6559143066406, 260.6337890625, 284.6474609375, 279.5469970703125, 271.0240173339844, 274.2396545410156, 301.18048095703125, 284.8901062011719, 299.6109924316406, 249.98435974121094, 268.5266418457031, 231.46495056152344, 268.3829040527344, 265.674072265625, 292.43310546875, 251.71826171875, 279.12261962890625, 281.6485900878906, 278.34210205078125, 283.3187561035156, 266.39459228515625, 278.9913024902344, 300.8293762207031, 301.5084533691406, 304.0146789550781, 271.0630187988281, 290.6606750488281, 259.51068115234375, 269.9560241699219, 271.8974609375, 234.51800537109375, 286.2940979003906, 242.18743896484375, 286.94146728515625, 269.3536376953125, 302.38739013671875, 282.7091369628906, 242.91726684570312, 292.6396789550781, 234.7799072265625, 259.156494140625, 272.7146301269531, 278.5467224121094, 296.4723205566406, 274.0387878417969, 287.9857177734375, 263.2049865722656, 250.65814208984375, 311.3221130371094, 308.1368713378906, 257.5716552734375, 258.6767883300781, 229.26901245117188, 241.60305786132812, 250.1350555419922, 240.27684020996094, 280.5903625488281, 261.2941589355469, 270.0325927734375, 273.39727783203125, 268.9554138183594, 323.5291442871094, 220.83026123046875, 259.7365417480469, 235.29144287109375, 265.3576354980469, 248.15382385253906, 256.3390808105469, 246.1334991455078, 258.8719482421875, 250.77220153808594, 313.29669189453125, 262.1786193847656, 288.1817321777344, 273.4465026855469, 261.78875732421875, 226.9951171875, 284.33050537109375, 271.8192443847656, 245.09774780273438, 257.9717102050781, 276.1273498535156, 288.6264343261719, 287.531494140625, 248.407958984375, 245.59750366210938, 238.09619140625, 272.9444274902344, 251.46832275390625, 259.41802978515625, 296.8205261230469, 275.9873352050781, 233.01934814453125, 271.1186828613281, 295.86187744140625, 253.77337646484375, 194.942626953125, 229.56033325195312, 278.22943115234375, 249.9022216796875, 269.7060852050781, 283.92901611328125, 268.07757568359375, 240.01336669921875, 212.43919372558594, 266.7933654785156, 235.69296264648438, 235.10174560546875, 247.90077209472656, 243.42599487304688, 236.98095703125, 283.5224304199219, 250.5489501953125, 243.0109405517578, 291.4216003417969, 208.96730041503906, 239.15232849121094, 258.2668762207031, 281.49700927734375, 236.41326904296875, 241.30038452148438, 236.251708984375, 257.77447509765625, 282.3089599609375, 223.09698486328125, 302.58184814453125, 279.593505859375, 234.5302734375, 257.75994873046875, 228.78363037109375, 248.10011291503906, 276.5100402832031, 215.35140991210938, 252.54345703125, 258.7406005859375, 245.97906494140625, 223.56552124023438, 255.25405883789062, 222.63369750976562, 303.1273498535156, 226.40003967285156, 232.42544555664062, 236.6880340576172, 271.3004455566406, 255.2328643798828, 240.2803497314453, 253.3459930419922, 283.18353271484375, 229.03744506835938, 232.2581787109375, 240.54669189453125, 274.82958984375, 246.46197509765625, 321.917724609375, 293.02825927734375, 267.3129577636719, 265.0782470703125, 266.62005615234375, 238.60739135742188, 215.39837646484375, 251.89466857910156, 238.20791625976562, 249.82003784179688, 230.15768432617188, 275.35003662109375, 290.6349792480469, 291.75396728515625, 257.86376953125, 261.8856201171875, 255.46620178222656, 252.5657958984375, 253.97418212890625, 243.90902709960938, 248.43263244628906, 239.99595642089844, 238.37353515625, 281.60235595703125, 268.0153503417969, 283.4459228515625, 274.219482421875, 241.1523895263672, 215.57537841796875, 251.19580078125, 245.2191162109375, 225.72882080078125, 305.96649169921875, 273.6109924316406, 259.2137451171875, 230.00926208496094, 292.7514953613281, 255.96717834472656, 263.99676513671875, 286.3486328125, 270.96282958984375, 275.4388427734375, 278.435546875, 294.02471923828125, 227.73583984375, 221.56503295898438, 258.77392578125, 226.81985473632812, 215.63856506347656, 251.10617065429688, 251.63723754882812, 245.38873291015625, 266.9097595214844, 263.0091247558594, 226.3712921142578, 252.64996337890625, 238.32717895507812, 292.54840087890625, 258.61163330078125, 274.4851989746094, 228.1827850341797, 286.1134338378906, 272.9149169921875, 233.39703369140625, 242.51873779296875, 238.83355712890625, 213.47219848632812, 263.26324462890625, 227.6112060546875, 289.72698974609375, 231.78001403808594, 233.8094024658203, 257.8643493652344, 259.83740234375, 231.46807861328125, 245.13491821289062, 275.5700988769531, 261.57080078125, 224.4208984375, 259.3220520019531, 225.9956817626953, 259.6398620605469, 238.7066650390625, 226.9607391357422, 267.49615478515625, 259.3399353027344, 238.85501098632812, 213.1292266845703, 233.099609375, 59.514617919921875, 211.3401336669922, 249.0919647216797, 265.6871337890625, 231.52984619140625, 291.91680908203125, 209.19839477539062, 246.7573699951172, 207.81903076171875, 210.3258514404297, 206.5991973876953, 282.7830810546875, 229.39398193359375, 272.7272033691406, 239.32394409179688, 272.1365051269531, 207.60008239746094, 257.1698913574219, 257.32891845703125, 220.27130126953125, 258.23150634765625, 221.95718383789062, 234.97018432617188, 251.49758911132812, 282.3830871582031, 197.232666015625, 253.47520446777344, 231.3600311279297, 237.8714599609375, 223.33270263671875, 257.16259765625, 230.04061889648438, 240.31179809570312, 232.47967529296875, 214.36163330078125, 237.00108337402344, 251.41217041015625, 232.35275268554688, 215.978515625, 270.0771484375, 279.5235595703125, 269.7814025878906, 263.62646484375, 252.1066436767578, 244.8670654296875, 231.3316650390625, 242.4128875732422, 220.68304443359375, 244.31427001953125, 242.6283721923828, 233.31637573242188, 211.55027770996094, 261.7132873535156, 205.6991729736328, 262.0177917480469, 252.4601593017578, 228.92698669433594, 245.7166748046875, 235.665283203125, 242.56246948242188, 243.34292602539062, 231.83441162109375, 206.1199951171875, 245.7801971435547, 214.162353515625, 232.28895568847656, 207.77987670898438, 241.69775390625, 239.3542938232422, 216.66773986816406, 231.4847412109375, 238.41075134277344, 250.88491821289062, 227.68115234375, 223.94268798828125, 252.22677612304688, 231.91256713867188, 257.7136535644531, 248.99557495117188, 233.5045928955078, 225.971435546875, 253.18960571289062, 225.12120056152344, 233.82948303222656, 205.37818908691406, 249.23126220703125, 233.04393005371094, 242.26878356933594, 244.36822509765625, 194.2965087890625, 220.1202392578125, 241.8286590576172, 280.5749816894531, 302.702880859375, 252.69354248046875, 210.35708618164062, 209.89501953125, 237.955322265625, 204.7120361328125, 229.77978515625, 264.6363830566406, 237.09458923339844, 289.531494140625, 223.64076232910156, 256.7222900390625, 227.36734008789062, 236.01441955566406, 250.30116271972656, 239.10244750976562, 245.84097290039062, 251.6678466796875, 223.19061279296875, 247.97915649414062, 242.8605194091797, 199.1187744140625, 250.54135131835938, 227.9842987060547, 210.22061157226562, 219.73995971679688, 212.16964721679688, 220.9947052001953, 241.335693359375, 232.43170166015625, 244.0616912841797, 280.33843994140625, 232.2574920654297, 225.816650390625, 248.7240753173828, 265.4443664550781, 222.12744140625, 228.1268768310547, 225.90504455566406, 224.1670379638672, 235.0028839111328, 227.21255493164062, 248.52536010742188, 219.36631774902344, 213.335205078125, 237.83802795410156, 254.01454162597656, 204.7191162109375, 239.1815948486328, 202.13006591796875, 207.14878845214844, 229.85948181152344, 208.20326232910156, 222.85922241210938, 211.85926818847656, 201.25057983398438, 245.29551696777344, 225.05886840820312, 219.36453247070312, 252.32540893554688, 225.8780517578125, 223.40219116210938, 210.87750244140625, 221.976806640625, 239.27505493164062, 243.03370666503906, 188.56103515625, 258.25457763671875, 206.58331298828125, 238.76551818847656, 220.95191955566406, 214.35377502441406, 221.73007202148438, 226.34481811523438, 213.83982849121094, 198.23883056640625, 216.63824462890625, 256.39520263671875, 248.9558563232422, 239.37164306640625, 244.0725555419922, 228.6702423095703, 234.75718688964844, 232.90187072753906, 217.20960998535156, 265.4905700683594, 228.12435913085938, 238.11624145507812, 226.8021240234375, 221.9906768798828, 225.46710205078125, 217.0240020751953, 226.6496124267578, 226.83233642578125, 230.11085510253906, 266.0708312988281, 226.16192626953125, 233.0563201904297, 236.25991821289062, 212.2574005126953, 208.89910888671875, 209.369140625, 267.6821594238281, 277.0679931640625, 215.51519775390625, 225.689697265625, 212.7451934814453, 201.9180145263672, 250.94500732421875, 207.94119262695312, 214.23731994628906, 270.6998291015625, 261.93402099609375, 236.52439880371094, 246.8148956298828, 246.62472534179688, 243.90731811523438, 259.8666687011719, 238.22802734375, 237.87661743164062, 225.11727905273438, 251.26318359375, 206.41200256347656, 218.28236389160156, 246.38250732421875, 260.626953125, 250.1890869140625, 252.0806121826172, 237.5680389404297, 231.3281707763672, 238.1372833251953, 217.44252014160156, 257.6673278808594, 195.76303100585938, 251.1087646484375, 214.1488800048828, 233.64170837402344, 263.3435974121094, 256.4784851074219, 256.3666076660156, 234.51461791992188, 221.40049743652344, 206.66806030273438, 226.84768676757812, 235.9622039794922, 235.72291564941406, 184.97850036621094, 192.25514221191406, 237.07412719726562, 227.73745727539062, 237.93661499023438, 229.79446411132812, 182.92274475097656, 242.6126251220703, 203.46389770507812, 222.72634887695312, 202.03128051757812, 233.632568359375, 219.39053344726562, 199.4194793701172, 241.31198120117188, 205.84759521484375, 234.43069458007812, 212.4256134033203, 214.05203247070312, 212.801025390625, 211.8062744140625, 200.86087036132812, 283.2816467285156, 201.9660186767578, 210.50559997558594, 221.1171417236328, 213.93414306640625, 197.17343139648438, 217.7969970703125, 257.27655029296875, 54.55677032470703, 217.80908203125, 274.2138671875, 209.37594604492188, 183.47972106933594, 197.12017822265625, 252.68170166015625, 192.77304077148438, 219.40060424804688, 234.88372802734375, 221.71780395507812, 225.11050415039062, 209.47030639648438, 211.24478149414062, 203.28553771972656, 234.60995483398438, 227.0824432373047, 205.61074829101562, 259.6377258300781, 241.30055236816406, 201.25173950195312, 189.19146728515625, 215.6863250732422, 205.45037841796875, 233.20010375976562, 178.5215606689453, 169.67276000976562, 188.95657348632812, 234.33055114746094, 215.359130859375, 226.003662109375, 223.16070556640625, 214.208251953125, 215.2548370361328, 242.75991821289062, 233.65731811523438, 264.8535461425781, 225.97637939453125, 218.3863525390625, 206.6111297607422, 247.38209533691406, 220.28713989257812, 238.29537963867188, 217.1735076904297, 222.1119384765625, 215.50408935546875, 216.3434295654297, 202.4103240966797, 209.5376434326172, 232.60008239746094, 221.6299285888672, 217.95770263671875, 230.278564453125, 227.04931640625, 213.16854858398438, 210.84512329101562, 256.6112365722656, 260.1543884277344, 231.38970947265625, 231.86526489257812, 213.08154296875, 233.8639678955078, 265.2184753417969, 228.09144592285156, 221.97866821289062, 207.65975952148438, 223.37734985351562, 187.86988830566406, 202.81689453125, 199.88079833984375, 226.81781005859375, 195.855712890625, 216.7611541748047, 225.41354370117188, 213.614013671875, 179.22970581054688, 217.61334228515625, 231.26385498046875, 178.35763549804688, 178.0717315673828, 225.12844848632812, 222.30682373046875, 175.70957946777344, 198.353271484375, 218.0124969482422, 238.41685485839844, 216.04702758789062, 186.69264221191406, 233.177001953125, 228.99951171875, 185.96192932128906, 233.34207153320312, 240.00439453125, 219.49920654296875, 217.94129943847656, 218.593017578125, 208.6614227294922, 224.91122436523438, 191.33474731445312, 206.28790283203125, 204.5965576171875, 254.15028381347656, 208.1638641357422, 228.72500610351562, 223.993896484375, 212.02980041503906, 219.1870574951172, 224.69236755371094, 213.17636108398438, 216.99374389648438, 201.04855346679688, 229.2057647705078, 224.07308959960938, 187.31680297851562, 229.51593017578125, 228.23098754882812, 231.50531005859375, 215.17648315429688, 212.64974975585938, 252.01881408691406, 206.72134399414062, 236.0158233642578, 228.41574096679688, 247.1437225341797, 234.56504821777344, 209.20620727539062, 234.77825927734375, 226.7553253173828, 237.59645080566406, 218.24996948242188, 220.11398315429688, 230.95498657226562, 213.45066833496094, 213.42935180664062, 246.34564208984375, 211.42906188964844, 244.8607177734375, 216.80398559570312, 233.02151489257812, 260.4437255859375, 213.44622802734375, 199.08233642578125, 188.70957946777344, 214.92745971679688, 259.72174072265625, 220.328857421875, 214.8976287841797, 239.7765655517578, 208.43760681152344, 213.42724609375, 235.10789489746094, 179.25225830078125, 196.0583038330078, 225.66339111328125, 217.0374755859375, 191.00567626953125, 200.64552307128906, 216.74154663085938, 220.46206665039062, 211.59796142578125, 194.93212890625, 259.7776794433594, 227.64796447753906, 216.80850219726562, 240.6885986328125, 181.16555786132812, 202.72903442382812, 201.7249755859375, 201.5113067626953, 188.2145538330078, 238.0596923828125, 242.1134033203125, 240.59617614746094, 202.50128173828125, 177.94155883789062, 243.45294189453125, 236.1197509765625, 202.60549926757812, 203.78797912597656, 238.2746124267578, 210.8278350830078, 209.39779663085938, 209.2200164794922, 185.85350036621094, 215.34182739257812, 202.4393310546875, 208.76939392089844, 193.34518432617188, 213.7749786376953, 235.61083984375, 188.40219116210938, 198.05419921875, 207.44451904296875, 228.1333770751953, 228.82675170898438, 192.4096221923828, 221.53652954101562, 213.39425659179688, 198.77532958984375, 244.7238006591797, 222.51498413085938, 219.46742248535156, 194.204833984375, 242.38304138183594, 181.5992889404297, 184.00015258789062, 241.4308319091797, 228.94308471679688, 213.74407958984375, 198.5611572265625, 208.73135375976562, 203.94482421875, 236.94393920898438, 248.7206268310547, 199.06211853027344, 206.2928009033203, 185.16409301757812, 223.02609252929688, 287.86260986328125, 199.51504516601562, 224.7344207763672, 186.10494995117188, 223.29635620117188, 208.41372680664062, 208.58189392089844, 227.010498046875, 231.83909606933594, 253.54364013671875, 234.5968475341797, 209.047607421875, 201.3260498046875, 185.692337036132

Rating: 100%|██████████| 20242/20242 [00:00<00:00, 199818.08it/s]

::::::
0.642102372245066

Ranking: 100%|██████████| 943/943 [00:00<00:00, 1393.22it/s]
Rating: 100%|██████████| 10371/10371 [00:00<00:00, 206113.04it/s]

::::::
0.6984495157208308

Ranking: 100%|██████████| 943/943 [00:00<00:00, 1927.07it/s]

[a=0 vae] Training started!

100%|██████████| 50/50 [00:02<00:00, 19.60it/s, loss=2.04]

[938.1690673828125, 935.9541625976562, 933.6814575195312, 931.41650390625, 929.1255493164062, 927.2802734375, 924.44677734375, 922.6417236328125, 920.4657592773438, 917.5988159179688, 915.5189208984375, 912.0890502929688, 909.7028198242188, 905.5108642578125, 901.800537109375, 900.9577026367188, 897.4356079101562, 891.224365234375, 888.0993041992188, 882.4684448242188, 877.73291015625, 872.8556518554688, 867.0697021484375, 860.73779296875, 860.225341796875, 847.7992553710938, 842.995361328125, 838.3211059570312, 827.9813232421875, 821.1854858398438, 811.1283569335938, 800.6401977539062, 793.3847045898438, 775.1875, 766.978271484375, 760.0341186523438, 739.42578125, 733.0980224609375, 709.5946655273438, 704.4429321289062, 680.12060546875, 655.8421020507812, 644.1915893554688, 644.3819580078125, 613.790771484375, 617.6981201171875, 582.8572998046875, 565.1700439453125, 552.5218505859375, 514.271728515625, 522.1781616210938, 532.7092895507812, 495.987060546875, 515.1836547851562, 438.42578125, 452.3745422363281, 448.116943359375, 411.346923828125, 410.6165466308594, 427.1759338378906, 389.97222900390625, 420.8036804199219, 360.93243408203125, 367.58355712890625, 386.3470764160156, 346.1866455078125, 351.9341735839844, 360.2601013183594, 313.11688232421875, 341.37091064453125, 303.43896484375, 308.49237060546875, 347.5672607421875, 304.5933837890625, 294.0486145019531, 309.7449035644531, 273.50927734375, 298.34454345703125, 261.91845703125, 274.4439697265625, 325.38995361328125, 273.0316162109375, 274.99945068359375, 277.2729187011719, 247.71273803710938, 268.97882080078125, 246.79043579101562, 245.04376220703125, 303.0965576171875, 246.4263153076172, 258.85797119140625, 269.8816223144531, 233.73875427246094, 253.99212646484375, 233.10089111328125, 241.0904083251953, 302.57806396484375, 237.1249542236328, 250.181640625, 256.2806701660156, 225.42880249023438, 241.49453735351562, 216.1215362548828, 228.8345184326172, 291.7994079589844, 233.45616149902344, 241.6504669189453, 261.13909912109375, 228.72865295410156, 242.08091735839844, 215.62437438964844, 229.5135955810547, 283.7588195800781, 228.6632080078125, 236.50616455078125, 251.42056274414062, 214.26736450195312, 235.1663055419922, 208.1512908935547, 236.84861755371094, 283.8702392578125, 226.4445343017578, 233.53965759277344, 239.22056579589844, 218.02566528320312, 229.42356872558594, 203.46334838867188, 225.17779541015625, 284.4326477050781, 222.30685424804688, 236.16522216796875, 248.1000518798828, 218.46173095703125, 229.42979431152344, 201.10816955566406, 220.67030334472656, 282.6904602050781, 219.70016479492188, 228.8818817138672, 241.65621948242188, 215.51065063476562, 226.10842895507812, 203.0750274658203, 216.07308959960938, 280.63494873046875, 220.5985870361328, 230.03187561035156, 240.35292053222656, 211.8403778076172, 228.530029296875, 200.20892333984375, 223.0234832763672, 279.53179931640625, 217.9971923828125, 232.00526428222656, 242.19923400878906, 209.38101196289062, 229.11984252929688, 197.8515167236328, 213.70816040039062, 274.1864318847656, 221.34295654296875, 230.88040161132812, 238.87362670898438, 207.9748992919922, 225.0733642578125, 195.12144470214844, 217.69015502929688, 277.91864013671875, 213.6952362060547, 226.62530517578125, 236.922607421875, 206.75697326660156, 226.07421875, 194.23370361328125, 211.5780029296875, 270.9727478027344, 216.57562255859375, 224.68560791015625, 243.04632568359375, 206.03575134277344, 219.3126678466797, 191.5405731201172, 209.6693878173828, 278.0620422363281, 212.13006591796875, 222.44517517089844, 239.40426635742188, 208.61508178710938, 220.50096130371094, 195.12069702148438, 212.9388885498047, 271.361083984375, 211.75721740722656, 224.86978149414062, 236.53802490234375, 203.99618530273438, 217.82252502441406, 193.60296630859375, 212.1821746826172, 273.4820861816406, 214.0232391357422, 226.60597229003906, 233.34225463867188, 203.3970489501953, 222.61000061035156, 191.5607452392578, 214.09341430664062, 274.127685546875, 211.68991088867188, 220.47023010253906, 232.316650390625, 204.39401245117188, 216.27796936035156, 192.96575927734375, 210.7618865966797, 268.970703125, 210.8313446044922, 221.34686279296875, 236.10032653808594, 201.39605712890625, 218.83309936523438, 191.73085021972656, 211.4850616455078, 270.0120849609375, 211.22947692871094, 223.8014678955078, 236.37301635742188, 205.56056213378906, 214.48153686523438, 190.15699768066406, 216.72938537597656, 271.8227844238281, 210.326416015625, 222.294677734375, 232.0882110595703, 200.3076171875, 219.32460021972656, 190.90969848632812, 212.8778076171875, 269.99993896484375, 210.621826171875, 222.7227020263672, 232.6984100341797, 201.91517639160156, 215.94935607910156, 188.5604705810547, 209.89291381835938, 267.9740295410156, 209.978759765625, 221.26991271972656, 230.6751251220703, 203.30613708496094, 212.2744598388672, 189.68577575683594, 210.5189666748047, 271.3111267089844, 209.05499267578125, 218.8426971435547, 232.2808074951172, 200.8349151611328, 212.31752014160156, 187.96920776367188, 209.5605926513672, 269.7705383300781, 206.7212677001953, 219.04632568359375, 229.12744140625, 201.03602600097656, 212.95883178710938, 189.1653289794922, 211.44705200195312, 264.6413269042969, 208.65289306640625, 218.1798095703125, 227.7419891357422, 201.07565307617188, 215.1325225830078, 187.20559692382812, 210.70066833496094, 265.9549865722656, 206.68431091308594, 220.6773681640625, 228.30657958984375, 197.91165161132812, 212.6357879638672, 188.3955535888672, 210.0004119873047, 265.0332946777344, 205.86984252929688, 217.44381713867188, 228.8885955810547, 198.29136657714844, 211.43736267089844, 186.5740966796875, 207.07943725585938, 265.6143798828125, 206.20428466796875, 216.02867126464844, 229.21498107910156, 197.60557556152344, 212.9559783935547, 186.56422424316406, 206.63796997070312, 265.682373046875, 204.692626953125, 216.4839630126953, 229.82833862304688, 197.00064086914062, 211.41893005371094, 186.11964416503906, 207.02687072753906, 265.24237060546875, 206.5707550048828, 216.47384643554688, 228.41110229492188, 197.41629028320312, 212.28427124023438, 188.9736328125, 204.29295349121094, 265.3435974121094, 206.43063354492188, 215.26361083984375, 228.3681640625, 197.6061553955078, 209.40896606445312, 185.87815856933594, 206.20948791503906, 264.04071044921875, 205.21206665039062, 214.27487182617188, 226.9938507080078, 196.7705078125, 211.99649047851562, 186.20008850097656, 208.15023803710938, 262.35589599609375, 205.5782928466797, 214.72254943847656, 227.2911834716797, 195.81271362304688, 209.3552703857422, 184.38124084472656, 205.24972534179688, 267.17083740234375, 203.80264282226562, 214.9028778076172, 227.08546447753906, 196.23561096191406, 209.98289489746094, 184.5351104736328, 202.92445373535156, 263.19915771484375, 206.1249542236328, 213.91610717773438, 225.3317108154297, 195.0733184814453, 209.08042907714844, 184.20541381835938, 206.76797485351562, 262.29388427734375, 205.24154663085938, 214.20565795898438, 224.79800415039062, 194.9246368408203, 209.43597412109375, 184.30047607421875, 201.0277557373047, 263.6230163574219, 203.80874633789062, 214.81979370117188, 226.21002197265625, 195.37191772460938, 208.7298583984375, 185.90232849121094, 202.00567626953125, 263.01043701171875, 202.87374877929688, 214.87379455566406, 226.0846710205078, 194.60256958007812, 206.367431640625, 183.265869140625, 202.9825897216797, 260.99285888671875, 202.50503540039062, 212.571533203125, 223.03404235839844, 194.64556884765625, 207.15667724609375, 182.144775390625, 202.5133819580078, 261.2818603515625, 202.5718994140625, 213.13331604003906, 222.31991577148438, 194.80270385742188, 206.94908142089844, 183.2240753173828, 203.88792419433594]

[a=0 vae] Evaluation started!

Rating: 100%|██████████| 20242/20242 [00:02<00:00, 7301.12it/s]

::::::
0.9071516970840109

Ranking: 100%|██████████| 943/943 [00:00<00:00, 1749.22it/s]
Rating: 100%|██████████| 10371/10371 [00:01<00:00, 7554.90it/s]

::::::
1.1588927684978116

Ranking: 100%|██████████| 943/943 [00:00<00:00, 1910.55it/s]

VALIDATION:
...
        |   RMSE |    AUC | HitRatio@50 |    MAP |    MRR | NDCG@50 | Precision@50 | Recall@50 | Time (s)
------- + ------ + ------ + ----------- + ------ + ------ + ------- + ------------ + --------- + --------
UserKNN | 0.9898 | 0.5806 |      0.3425 | 0.0168 | 0.0261 |  0.0247 |       0.0102 |    0.0553 |   2.6134
ItemKNN | 1.0549 | 0.5430 |      0.3521 | 0.0165 | 0.0418 |  0.0272 |       0.0117 |    0.0481 |   4.3904
a=0 mf  | 0.9421 | 0.5714 |      0.5249 | 0.0320 | 0.1091 |  0.0667 |       0.0223 |    0.1112 |   0.5955
a=0 vae | 2.6818 | 0.7789 |      0.7678 | 0.0602 | 0.1722 |  0.1303 |       0.0397 |    0.2351 |   1.9142

TEST:
...
        |   RMSE |    AUC | HitRatio@50 |    MAP |    MRR | NDCG@50 | Precision@50 | Recall@50 | Train (s) | Test (s)
------- + ------ + ------ + ----------- + ------ + ------ + ------- + ------------ + --------- + --------- + --------
UserKNN | 1.0087 | 0.5801 |      0.4931 | 0.0287 | 0.0406 |  0.0321 |       0.0200 |    0.0544 |    0.0523 |   3.4204
ItemKNN | 1.0782 | 0.5376 |      0.4698 | 0.0270 | 0.0678 |  0.0347 |       0.0226 |    0.0465 |    0.0853 |   5.0855
a=0 mf  | 0.9639 | 0.5757 |      0.6469 | 0.0495 | 0.1834 |  0.0887 |       0.0441 |    0.1107 |    2.6839 |   0.9021
a=0 vae | 2.6857 | 0.7817 |      0.8749 | 0.0889 | 0.2662 |  0.1643 |       0.0761 |    0.2294 |    2.5789 |   3.3748

In [31]:
neumf_0_reco_matrix_all = np.load("results/neumf100k/neumf_reco_matrix_all.npy")
neumf_0_reco_matrix = np.load("results/neumf100k/neumf_reco_matrix.npy")
# /Users/tahsinalamgirkheya/Desktop/work/cornac-reco/results/neumf100k/ml_100k_mf copy 2.png

In [19]:
user_ids = users.to_numpy()[:, 1]
item_ids = movies.to_numpy()[:, 2]
item_ids.__len__()
# get the top_k ratings for all users:
top_k = 50
reco_matrix = np.zeros((len(models)+1, len(user_ids), top_k), dtype=int)
reco_matrix_mapped_items = np.zeros(
    (len(models), len(user_ids), len(item_ids)), dtype=int
)
reco_matrix_mapped_scores = np.zeros(
    (len(models), len(user_ids), len(item_ids)), dtype=float
)
reco_matrix_all = np.zeros((len(models)+1, len(user_ids), len(item_ids)), dtype=int)


for u in user_ids:
    for i in range(len(models)):
        reco_items = models[i].recommend(u)
        items_mapped, mapped_scores = models[i].rank(
            user_idx=u, item_indices=list(item_ids)
        )
        reco_matrix_mapped_items[i][u] = items_mapped
        reco_matrix_mapped_scores[i][u] = mapped_scores
        reco_matrix_all[i][u] = reco_items
        reco_matrix[i][u] = reco_items[:top_k]

        # print(reco_matrix[0][3])

In [34]:
reco_matrix[4] = neumf_0_reco_matrix[0]

In [36]:
reco_matrix_all[4] = neumf_0_reco_matrix_all[0]

In [39]:

np.save("reco_matrix_100k_all_models.npy", reco_matrix)
np.save("reco_matrix_100k_all_models_all.npy", reco_matrix_all)

In [41]:
reco_matrix[0][2]

array([1319, 1150, 1305,  630, 1215, 1192, 1048,    0,    1, 1173, 1268,
        180, 1180,  922,  359,  520, 1148,  510,  200,   58,  807, 1006,
        654, 1034,  624,  101, 1162,  367, 1060, 1321,  873,  536,   30,
        666,  765,  486,   36,   52, 1208,  938, 1245, 1002,  102,  277,
       1345,  589,  130, 1223,  407,  216])